### ISSUE TITLE
[2] Requirements

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#100]
### **Description:** 

- Task ID: 2

- Task Detail:  Get all the requirements needed for the project

- Task Goals: Gather all the requirements

- Success/Completion Criteria: When all the requirements are gathered

- Allocated Time: 16 Days

- Start/End Date: 05/09/23 - 26/09/23

- Owner: 
  All -> [2.1]
  Calvin -> [2.2], [2.3]
  Tan Zining, Jessaryn -> [2.4]
  Victor, Jessaryn -> [2.5]
  Victor, Jessaryn, Ying Zhen -> [2.6]
  Tan Zining -> [2.7]
  All -> [2.8]
  Calvin, Ying Zhen -> [2.9]

- Task Status:  To-Do

- Task Priority: High

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [2.1]  completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 5/09/23 - 26/09/23

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [2.4], [2.5]completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 11/09/23 - 21/09/23

**Comment by CalvinLeow** [comment]
### **Progress Update**

- Work Done: [2.2], [2.3], [2.8], [2.9] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 11/09/23 - 23/09/23

**Comment by CalvinLeow** [comment]
### **Task Completion**

- Work Done: [2.6], [2.7] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 19/09/23 - 22/09/23
