### ISSUE TITLE
[2.6.2] Prepare Gantt Chart

### ISSUE THREAD

**Issue by LeeYingZhen** [Vict0rK/INF2001_P5-6#103]
**Description**

Task ID: 2.6.2

Task Detail: Input owners, reorganize with reference to WBS, prepare dates of tasks, assign progress bar

Task Goals: Finish input owners, reorganize with reference to WBS, prepare dates of tasks, assign progress bar

Success/Completion Criteria: upon completion

Allocated Time: 4 Days

Start/End Date: 19/9/23 - 22/9/23

Owner:
Victor -> [2.6.2.1]
Jessaryn -> [2.6.2.2]
Ying Zhen -> [2.6.2.3], [2.6.2.4]

Task Status: To-Do

Task Priority: High

**Comment by LeeYingZhen** [comment]
**Progress Update**

Work Done: [2.6.2.3], [2.6.2.4] completed

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 22/09/2023

**Comment by Vict0rK** [comment]
**Progress Update**

Work Done: [2.6.2.1] completed

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 22/09/2023

**Comment by name54321** [comment]
Progress Update

Work Done: [2.6.2.2] completed

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 22/09/2023

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: everything done 

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 22/09/2023
