### ISSUE TITLE
[3.2.1] Class Diagram

### ISSUE THREAD

**Issue by LeeYingZhen** [Vict0rK/INF2001_P5-6#115]
**Description**

Task ID: 3.2.1

Task Detail: Come up with the ECB and complete the Class Diagram.

Task Goals: Complete the Class Diagram.

Success/Completion Criteria: Upon completion

Allocated Time: 9 Days

Start/End Date: 16/10/2023 - 26/10/2023

Owner:
Calvin -> [3.2.1.1]
Ying Zhen -> [3.2.1.2]
Victor -> [3.2.1.3], [3.2.1.4]
Zining -> [3.2.1.5], [3.2.1.6]
Jessaryn -> [3.2.1.7], [3.2.1.8] 

Task Status: To-Do

Task Priority: Medium

**Comment by LeeYingZhen** [comment]
**Progress Update**

Work Done: [3.2.1.2] completed

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 26/10/2023

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [3.2.1.7], [3.2.1.8] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 16/10/23 - 26/10/23

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [3.2.1.3], [3.2.1.4] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 20/10/23

**Comment by name54321** [comment]
- Work Done: [3.2.1.1], [3.2.1.5], [3.2.1.6] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 16/10/23 - 26/10/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: Class Diagram. Done

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 16/10/23 - 26/10/23
