### ISSUE TITLE
[3.1.1] Component Diagram

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#125]
**Description:** 

- Task ID: 3.1.1

- Task Detail: Create Component Diagram

- Task Goals:  Component Diagram

- Success/Completion Criteria: When Component Diagram Completed

- Allocated Time: 9 Day

- Start/End Date: 16/10/23 - 26/10/23

- Owner:  
  Zining -> [3.1.1.1]
  Victor -> [3.1.1.2]
  Jessaryn -> [3.1.1.3]

- Task Status: Completed

- Task Priority: Medium

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [3.1.1.3] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 16/10/23 - 26/10/23

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [3.1.1.2] completed

- Committed to Repo: (NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 26/10/23

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [3.1.1.1] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 16/10/23 - 26/10/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: Component Diagram Completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 16/10/23 - 26/10/23
