### ISSUE TITLE
[3.2.2.1] Allocate Job Use Case

### ISSUE THREAD

**Issue by Vict0rK** [Vict0rK/INF2001_P5-6#135]
**Description:** 

- Task ID: 3.2.2.1

- Task Detail: Create Job Use Case Sequence Diagram

- Task Goals: Job Use Case Sequence Diagram

- Success/Completion Criteria: When Job Use Case Sequence Diagram Completed

- Allocated Time: 5 Day

- Start/End Date: 23/10/23 - 27/10/23

- Owner:  
 Victor -> [3.2.2.1.1]
 Jessaryn ->[3.2.2.1.2]

- Task Status: Completed

- Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Progress Updated**

- Work Done: [3.2.2.1.1]

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 23/10/23

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [3.2.2.1.2] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 23/10/23 - 27/10/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: Job Use Case completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 23/10/23 - 27/10/23
