### ISSUE TITLE
[3.2.2] Sequence Diagram

### ISSUE THREAD

**Issue by Vict0rK** [Vict0rK/INF2001_P5-6#137]
**Description:** 

- Task ID: 3.2.2

- Task Detail: Create sequence diagram 

- Task Goals: detailed sequence diagram

- Success/Completion Criteria: When the sequence diagrams are completed

- Allocated Time: 4 Days

- Start/End Date: 23/10/23 - 27/10/23

- Owner:  
Victor, Jess -> [3.2.2.1]
Zining, Ying Zhen -> [3.2.2.2]

- Task Status: Completed

- Task Priority: Medium

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [3.2.2.1] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 23/10/23 - 27/10/23

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [3.2.2.2] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 23/10/23 - 27/10/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: Sequence diagram Done

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 23/10/23 - 27/10/23
