### ISSUE TITLE
[3.7] M2 Presentation

### ISSUE THREAD

**Issue by zininngg** [Vict0rK/INF2001_P5-6#138]
Description

Task ID: 3.7

Task Detail: Create presentation slides and prepare for M2 presentation

Task Goals: Be well prepared for M2 presentation

Success/Completion Criteria: Slides and script created for a 5 min M2 presentation and Q&A including System overview, Updates/Changes and rationale, Class Diagram, Component Diagram, Sequence Diagram, Updated Project Plan

Allocated Time: 1 days

Start/End Date: 31/10/23 - 31/10/23

Owner:
Zining [3.7.1], [3.7.2], [3.7.3]
Jessaryn [3.7.4], [3.7.5], [3.7.6]

Task Status: To-Do

Task Priority: High

**Comment by name54321** [comment]
### **Progress Update**

- Work Done:  [3.7.1], [3.7.2], [3.7.3] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 31/10/23 - 31/10/23

**Comment by name54321** [comment]
### **Progress Update**

- Work Done:  [3.7.4], [3.7.5], [3.7.6] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 31/10/23 - 31/10/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: M2 Presentation Done

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 31/10/23 - 31/10/23
