### ISSUE TITLE
[5.4.2] Detailed Design

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#148]
**Description:** 

- Task ID: 5.4.2

- Task Detail: Detailed Design

- Task Goals: Detailed Design

- Success/Completion Criteria: When Detailed Design Completed

- Allocated Time: 1 Day

- Start/End Date: 24/11/23 - 24/11/23

- Owner:  Victor

- Task Status: Completed

- Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Task Completion**

- Work Done:  Detailed Design completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 24/11/23
