### ISSUE TITLE
[5.4.1] Architecture Design

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#149]
**Description:** 

- Task ID: 5.4.1

- Task Detail: Architecture Design
- Task Goals: Architecture Design

- Success/Completion Criteria: When Architecture Design Completed

- Allocated Time: 1 Day

- Start/End Date: 24/11/23 - 24/11/23

- Owner:  Victor

- Task Status: Completed

- Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Task Completion**

- Work Done: Architecture Design completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 24/11/23
