### ISSUE TITLE
[5.4] M3

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#150]
**Description:** 

- Task ID: 5.4

- Task Detail: Complete Phase m3
- 
- Task Goals: to finish all diagrams

- Success/Completion Criteria: When M3 Completed

- Allocated Time: 1 Day

- Start/End Date: 24/11/23 - 24/11/23

- Owner:  Victor [5.4.1, 5.4.2, 5.4.3]

- Task Status: Completed

- Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Task Completion**

- Work Done: M3 Completed [5.4.1, 5.4.2, 5.4.3]

- Committed to Repo: NA

- Completion Dateline Affected: N
- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 24/11/23
