### ISSUE TITLE
[5.2] White Box

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#152]
**Description:** 

- Task ID: 5.5.3

- Task Detail: White Box

- Task Goals: White Box testing

- Success/Completion Criteria: When White Box Testing Completed

- Allocated Time: 3 Day

- Start/End Date: 15/11/23 - 17/11/23

- Owner:  
 Victor-> [5.2.1]
 Zining -> [5.2.2]
 Jessaryn -> [5.2.3]
 Ying Zhen -> [5.2.4]
 

- Task Status: To-Do

- Task Priority: Medium

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [5.2.3] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 15/11/23 - 17/11/23

**Comment by LeeYingZhen** [comment]
### **Progress Update**

- Work Done: [5.2.4] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 15/11/23 - 17/11/23

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [5.2.1] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 13/11/23 - 15/11/23
