### ISSUE TITLE
[5.2.1] Create Test Cases

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#153]
**Description:** 

- Task ID: 5.2.1

- Task Detail: Create Test Cases

- Task Goals: Create Test Cases

- Success/Completion Criteria: When Create Test Cases Completed

- Allocated Time: 3 Day

- Start/End Date: 15/11/23 - 17/11/23

- Owner:  Victor

- Task Status: Completed

- Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Task Completion**

- Work Done: test cases completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N 

- Start/End Date of Update Work: 17/11/23
