### ISSUE TITLE
[5.2.4] Conduct Integration Test

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#156]
**Description:** 

- Task ID: 5.2.4

- Task Detail: Conduct Integration Test

- Task Goals: Conduct Integration Test

- Success/Completion Criteria: When Integration Test Conducted

- Allocated Time: 3 Day

- Start/End Date: 15/11/23 - 17/11/23

- Owner:  Yingzhen

- Task Status: To-Do

- Task Priority: Medium

**Comment by LeeYingZhen** [comment]
### **Task Completion**

- Work Done: Integration Test conducted

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 15/11/23 - 17/11/23
