### ISSUE TITLE
[5.1] Black Box

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#158]
**Description:** 

- Task ID: 5.1

- Task Detail: Black Box

- Task Goals: Black Box testing 

- Success/Completion Criteria: When black box testing is Completed

- Allocated Time: 3 Day

- Start/End Date: 13/11/23 - 15/11/23

- Owner:  
Jessaryn -> [5.1.1]
Yingzhen -> [5.1.2]
Victor -> [5.1.3]
Zining -> [5.1.4]

- Task Status: To-Do

- Task Priority: Medium

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [5.1.1] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 13/11/23 - 15/11/23

**Comment by LeeYingZhen** [comment]
### **Progress Update**

- Work Done: [5.1.2] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 13/11/23 - 15/11/23

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [5.1.3] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 13/11/23 - 15/11/23
