### ISSUE TITLE
[5.1.2] Create Test Scenario

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#160]
**Description:** 

- Task ID: 5.1.2

- Task Detail: Create Test Scenario for Black Box

- Task Goals: Create Test Scenario for Black Box testing 

- Success/Completion Criteria: When test Scenario is Completed

- Allocated Time: 3 Day

- Start/End Date: 13/11/23 - 15/11/23

- Owner:  Yingzhen

- Task Status: To-Do

- Task Priority: Medium

**Comment by LeeYingZhen** [comment]
**Task Completion**

Work Done: Test Scenario for Black Box Done

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 13/11/23 - 15/11/23
