### ISSUE TITLE
[5.1.3] Conduct Functional Test

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#161]
**Description:** 

- Task ID: 5.1.3

- Task Detail: Conduct Functional Test for Black Box

- Task Goals: Create Conduct Functional Test for Black Box testing 

- Success/Completion Criteria: When Functional Test Completed

- Allocated Time: 3 Day

- Start/End Date: 13/11/23 - 15/11/23

- Owner:  Victor

- Task Status: Completed

- Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Task Completion**

- Work Done: Functional Test

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 15/11/23
