### ISSUE TITLE
[3.8] UI Prototype

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#163]
Description:

Task ID: 3.8

Task Detail: Create UI Prototype

Task Goals: Create UI Prototype

Success/Completion Criteria: When UI Prototype Completed

Allocated Time: 8 Day

Start/End Date: 30/10/23 - 08/11/23

Owner:
Zining [3.8.1]
Victor [3.8.2]
Calvin [3.8.3]

Task Status: Completed

Task Priority: Medium

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [3.8.2] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 08/11/23

**Comment by CalvinLeow** [comment]
### **Task Completion**

- Work Done: [3.8.1][3.8.3]

- Committed to Repo: NA

- Completion Dateline Affected: No

- Changes to Success/Completion Criteria: No

- Start/End Date of Update Work: 08/11/23
