### ISSUE TITLE
[2.4.1] Use Case Model

### ISSUE THREAD

**Issue by zininngg** [Vict0rK/INF2001_P5-6#23]
**Description**

Task ID: 2.4.1

Task Detail: Create a Use Case model and explain your use case diagram to aid understanding of your concepts. 

Task Goals: Use Case Model to accurately and comprehensively represent the functionality of the system.
Ensure that all relevant actors are identified and that their interactions with the system are properly defined in the diagram

Success/Completion Criteria: when documented

Allocated Time: 16 day

Start/End Date: 8/9/23 - 23/9/23

Owner: Tan Zining

Task Status: Completed

Task Priority: HIGH

**Comment by name54321** [comment]
**Task Completion**

-Work Done: Use Case model done

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work:  8/9/23 - 23/9/23
