### ISSUE TITLE
[6.5] References and Acknowledgement

### ISSUE THREAD

**Issue by LeeYingZhen** [Vict0rK/INF2001_P5-6#28]
**Description**

- Task ID: 6.5

- Task Detail: Document the References and Acknowledgement, this will list any other documents or Web addresses to which this document refers.

- Task Goals: To be able to list down any materials or documents we refer/use.

- Success/Completion Criteria: when documented

- Allocated Time: 10 days

- Start/End Date: 5/9/23 - 15/9/23

- Owner: Ying Zhen, Jessaryn

- Task Status: In-Progress

- Task Priority: MEDIUM

**Comment by LeeYingZhen** [comment]
Task Completion

Work Done: All references have been documented under section References and Acknowledgement.

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 15/09/2023

**Comment by name54321** [comment]
**Task Completion**

- Work Done: All references have been documented under section References and Acknowledgement.

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 15/09/2023
