### ISSUE TITLE
[2.6.1] Prepare WBS

### ISSUE THREAD

**Issue by Vict0rK** [Vict0rK/INF2001_P5-6#37]
### **Description**

- Task ID: 2.6.1

- Task Detail: come up with gantt chart of the WBS, this WBS will do a breakdown of what our timeline is going to be from M1 all the way to M3

- Task Goals: to understand and come up with the project timeline so that our clients and project managers are able to determine the feasibility of this project.

- Success/Completion Criteria: upon completion

- Allocated Time: 3 Days

- Start/End Date: 19/9/23 - 22/9/23 

- Owner: 
Victor -> [2.6.1.1]
Jessaryn -> [2.6.1.2]
Ying Zhen -> [2.6.1.3]

- Task Status: To-Do

- Task Priority: High

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [2.6.1.1] completed

- Committed to Repo: NA
- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 22/09/23

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [2.6.1.2] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 19/9/23 - 22/9/23

**Comment by LeeYingZhen** [comment]
**Progress Update**

Work Done: [2.6.1.3] completed

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 19/9/23 - 22/9/23

**Comment by LeeYingZhen** [comment]
**Task Completion**

-Work Done: Everything done

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 19/09/23 - 22/09/23
