### ISSUE TITLE
[2.9] M1 Presentation

### ISSUE THREAD

**Issue by CalvinLeow** [Vict0rK/INF2001_P5-6#39]
### **Description**

- Task ID: 2.9

- Task Detail: Create presentation slides and prepare for M1 presentation

- Task Goals: Be well prepared for M1 presentation

- Success/Completion Criteria: Slides and script created for a 5 min M1 presentation and Q&A including System overview, Requirements Discovery Methods and key findings, Use case Diagram, Explain your chosen SDLCs, Project estimation and planning

- Allocated Time: 6 days

- Start/End Date: 19/09/23 - 26/09/23

- Owner:
Calvin [System Overview 2.9.1][Requirements Discovery Methods and Key Findings 2.9.2][Chosen SDLCs 2.9.4]
Ying Zhen [Use Case Diagram 2.9.3][Project Estimation and Planning 2.9.5]

- Task Status: To-Do

- Task Priority: High

**Comment by LeeYingZhen** [comment]
**Progress Update**

-Work Done: [2.9.3], [2.9.5] completed

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 23/09/2023

**Comment by CalvinLeow** [comment]
**Task Completion**

-Work Done: [2.9.1], [2.9.2], [2.9.4] completed

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 23/09/2023
