### ISSUE TITLE
[1.1] Set up Git

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#42]
**Description:** 

- Task ID: 1.1

- Task Detail: Create the group's GitHub repo and add all the members inside

- Task Goals: Github Repo and Kanban board

- Success/Completion Criteria: Github Repo and Kanban board created

- Allocated Time: 1 Day

- Start/End Date: 29/08/23 - 29/08/23

- Owner: 
  Victor -> [1.1.1], [1.1.2]
  Calvin -> [1.1.3], [1.1.4]

- Task Status: Completed

- Task Priority: Medium

**Comment by name54321** [comment]
**Task Completion**

-Work Done: Group's GitHub repo created with all the members added

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23

**Comment by CalvinLeow** [comment]
### **Progress Update**

- Work Done: [1.1.3] and [1.1.4] Completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 29/08/23

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [1.1.1] and [1.1.2] Completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 29/08/23
