### ISSUE TITLE
[1.1.2] Add Team Members

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#44]
**Description:** 

- Task ID: 1.1.2

- Task Detail: Add all the group member into the Github Repo
- 
- Task Goals: Add all the members

- Success/Completion Criteria: All member added

- Allocated Time: 1 Day

- Start/End Date: 29/08/23 - 29/08/23

- Owner: Victor

- Task Status: Completed

- Task Priority: Low

**Comment by name54321** [comment]
**Task Completion**

-Work Done: Group member added into group's Github Repo

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23

**Comment by Vict0rK** [comment]
**Task Completion**

-Work Done: Group member added into group's Github Repo

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23
