### ISSUE TITLE
[1.2] Set Up Kanban

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#45]
**Description:** 

- Task ID: 1.2
- Task Detail: Create a kanban board inside the github repo for the team

- Task Goals: Create a kanban board

- Success/Completion Criteria: Kanban board created

- Allocated Time: 1 Day

- Start/End Date: 29/08/23 - 23/09/23

- Owner: 
   Victor ->[1.2.1]

- Task Status: Completed

- Task Priority: Low

**Comment by name54321** [comment]
**Task Completion**

-Work Done: Kanban board created inside the github repo

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23

**Comment by Vict0rK** [comment]
**Task Completion**

-Work Done: Kanban board created inside the github repo

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23
