### ISSUE TITLE
[2.1.4] Send Second Email

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#60]
Description
Task ID: 2.1.4

Task Detail: send out the second email containing follow up questions

Task Goals: Send out second email with follow up questions

Success/Completion Criteria: Second email sent

Allocated Time: 1 Day

Start/End Date: 13/09/23 - 13/09/23

Owner: Victor

Task Status: To-Do

Task Priority: High Priority

**Comment by name54321** [comment]
Task Completion

-Work Done: Second email sent out to client

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 13/09/23 - 13/09/23

**Comment by Vict0rK** [comment]
Task Completion

-Work Done: Second email sent out to client

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 13/09/23 - 13/09/23
