### ISSUE TITLE
[2.4.2.1] Use Case Description 1 to 8

### ISSUE THREAD

**Issue by zininngg** [Vict0rK/INF2001_P5-6#62]
**Description**

Task ID: 2.4.2.1

Task Detail: Provide a comprehensive description that includes preconditions, main flow, alternative flows, post-conditions, and any additional relevant information for each use case.

Task Goals: Ensure that each use case description accurately outlines the conditions that must be met for the use case to be executed.
Provide a step-by-step description of the primary sequence of actions that occur when the use case is executed.
Document any deviations or variations from the main flow, indicating how the system handles exceptional conditions.
Provide a detailed understanding of how the system functions in various situations.

Success/Completion Criteria: when documented

Allocated Time: 13 Days

Start/End Date: 11/9/23 - 23/9/23

Owner: Tan Zining

Task Status: Completed

Task Priority: MEDIUM

**Comment by name54321** [comment]
**Task Completion**

-Work Done: Usecase description completed

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 11/9/23 - 23/9/23
