### ISSUE TITLE
[1.1.1] Create Git Repository

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#66]
**Description:** 

- Task ID: 1.1.1

- Task Detail: Create a Git repository for the team to update their progress

- Task Goals: Create a Git repository

- Success/Completion Criteria: git repository created

- Allocated Time: 1 Day

- Start/End Date: 29/08/23 - 29/08/23

- Owner: Victor

- Task Status: Completed

- Task Priority: Low

**Comment by name54321** [comment]
**Task Completion**

-Work Done: git repository created

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23 - 29/08/23

**Comment by Vict0rK** [comment]
**Task Completion**

-Work Done: git repository created

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 29/08/23 - 29/08/23
