### ISSUE TITLE
[2.5] Software Estimation

### ISSUE THREAD

**Issue by Vict0rK** [Vict0rK/INF2001_P5-6#92]
### **Description**

- Task ID: 2.5
 
- Task Detail: Discuss the process of estimating the time and resources needed for our project. We will be calculating using Use Case Points (UCP) as our chosen method for estimation as it is the most suitable for our project considering we do not have any lines of code (LOC) or functions to use for function points (FP).

- Task Goals: to calculate the software estimation

- Success/Completion Criteria: upon completion

- Allocated Time: 2 Days

- Start/End Date: 20/9/23 - 22/9/23

- Owner:
Victor -> [2.5.1][2.5.2][2.5.3][2.5.6]
Jessaryn -> [2.5.4][2.5.5]

- Task Status: To-Do

- Task Priority: High

**Comment by Vict0rK** [comment]
### **Progress Update**

- Work Done: [2.5.1][2.5.2][2.5.3][2.5.6] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 20/9/23 - 22/9/23

**Comment by name54321** [comment]
**Progress Update**

-Work Done: [2.5.4], [2.5.5] completed

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 20/9/23 - 22/9/23

**Comment by name54321** [comment]
**Task Completion**

-Work Done: Everything for software estimation completed

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 0/9/23 - 22/9/23
