### ISSUE TITLE
[2.1] Requirements Gathering

### ISSUE THREAD

**Issue by LeeYingZhen** [Vict0rK/INF2001_P5-6#94]
**Description**

Task ID: 2.1

Task Detail: Come up with a list of questions based on the requirements, consolidate the questions, send email to clients to clarify on the requirements.

Task Goals: Interview questions are consolidated and clarified.

Success/Completion Criteria: Upon completion

Allocated Time: 7 Days

Start/End Date: 05/09/2023 - 13/09/2023

Owner:
Calvin -> [2.1.1]
Ying Zhen -> [2.1.2]
Victor -> [2.1.3], [2.1.4]

Task Status: To-Do

Task Priority: Medium

**Comment by LeeYingZhen** [comment]
**Progress Update**

Work Done: [2.1.2] completed

Committed to Repo: NA

Completion Dateline Affected: N

Changes to Success/Completion Criteria: N

Start/End Date of Update Work: 13/09/2023

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [2.1.1], [2.1.3], [2.1.4], [2.1.5] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 5/09/23 - 26/09/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: Requirements Gathering Done

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 05/09/2023 - 13/09/2023
