### ISSUE TITLE
[2.6] Project Planning

### ISSUE THREAD

**Issue by name54321** [Vict0rK/INF2001_P5-6#97]
**Description:** 

- Task ID:  2.6

- Task Detail:  Prepare WBS, Gantt Chart and SDLC cycle

- Task Goals:  Prepare WBS, Gantt Chart and SDLC cycle

- Success/Completion Criteria: When all are completed

- Allocated Time: 4 Days

- Start/End Date: 19/09/23 - 22/09/23

- Owner:  
  Victor, Jessaryn, Ying Zhen -> [2.6.1]
  Victor, Jessaryn, Ying Zhen -> [2.6.2]
   Jessaryn -> [2.6.3]

- Task Status: To-Do

- Task Priority: High

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [2.6.3] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 22/09/23

**Comment by LeeYingZhen** [comment]
**Progress Update**

-Work Done: [2.6.1] completed

-Committed to Repo: NA

-Completion Dateline Affected: N

-Changes to Success/Completion Criteria: N

-Start/End Date of Update Work: 22/09/2023

**Comment by name54321** [comment]
### **Progress Update**

- Work Done: [2.6.2] completed

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 22/09/23

**Comment by name54321** [comment]
### **Task Completion**

- Work Done: Everything done

- Committed to Repo: NA

- Completion Dateline Affected: N

- Changes to Success/Completion Criteria: N

- Start/End Date of Update Work: 22/09/23
